services:

    domain.events.publisher:
        class: MR\DoctrineDomainEventsBundle\EventBus\DomainEventsPublisher
        arguments:
            - "@event_bus"
            - "@simple_bus.doctrine_orm_bridge.collects_events_from_entities"
        tags:
            -  { name: kernel.event_listener, event: kernel.response, method: publishEvents }
            -  { name: kernel.event_listener, event: console.terminate, method: publishEvents }